version: "3.1"
services:
  expoterhub:
    image: nexclipper/exporterhub:latest
    ports:
      - "8080:3000"
    depends_on:
      - api
  maria_db:
    image: mariadb:10.4.17
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: exporterhub
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    volumes:
      - ./db_data:/var/lib/mysql/
  scheduler:
    image: nexclipper/exporterhub-api:latest
    restart: always
    environment:
      APP_DB_ENGINE: django.db.backends.mysql
      DB_NAME: exporterhub
      DB_USER: root
      DB_PASSWORD: secret
      DB_HOST: maria_db
      DB_PORT: "3306"
      APP_STAT: "scheduler"
      SECRET_KEY: "supersecretkey"
    depends_on:
      - maria_db
      - api
  api:
    image: nexclipper/exporterhub-api:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      APP_DB_ENGINE: django.db.backends.mysql
      DB_NAME: exporterhub
      DB_USER: root
      DB_PASSWORD: secret
      DB_HOST: maria_db
      DB_PORT: "3306"
      SECRET_KEY: "supersecretkey"
      APP_STAT: "server"
    depends_on:
      - maria_db
